### ISSUE TITLE
[Proposed Feature] GitHub Actions for Deployments

### ISSUE THREAD

**Issue by kbgg** [source-cooperative/data.source.coop#10]
**Description of Feature:**

We should set up GitHub actions to automatically build the image, push to ECR, and deploy to ECS upon tagging a release.

Additionally, we should consider how to handle rollbacks.

**What value is this feature adding to Source Cooperative?**

Automated deployments will speed up the process of deploying updates as well as reduce the risk of human error in the deployment process.

**Comment by kbgg** [comment]
[This](https://jkrsp.com/deploy-and-rollback-releases-with-github-actions/) is probably a good strategy for rollbacks

**Comment by navdeepg2021** [comment]
@kbgg I was actually planning to work on it, but its fine if you think that you want to add this stuff. Let me know the aws role name and I can add it for deploy purpose.

We should use (release-please)[https://github.com/google-github-actions/release-please-action] to start with release creation on checkin to main branch and subsequently deploy the changes to prod environment.

**Comment by navdeepg2021** [comment]
Implemented.
