### ISSUE TITLE
[Proposed Feature] Implement ListObjectsV2 at the "account" level

### ISSUE THREAD

**Issue by kbgg** [source-cooperative/data.source.coop#17]
**Description of Feature:**

Currently, we allow users to list objects from within a repository. If the user wants to explore all of the repositories a specific account has however, this is not possible from within the Source Cooperative Data Proxy. We should implement this endpoint such that users can run the `aws s3 ls s3://{ACCOUNT_ID}` endpoint and receive a list of that account's repositories.

For example: there is an account on Source Cooperative (`radiantearth`) which has the repositories `radiantearth/landcovernet` and `radiantearth/african-crops-01`.
The response should be something like this:
```
> aws s3 ls s3://radiantearth
                           PRE landcovernet/
                           PRE african-crops-01/
```

**What value is this feature adding to Source Cooperative?**

Along with #16 this would enable users to explore the entirety of the Source Cooperative repository collection through the AWS CLI.

**Comment by navdeepg2021** [comment]
Implemented and deployed.
