### ISSUE TITLE
[Bug] Calls to Source Cooperative API call unimplemented route when empty AWS_ACCESS_KEY_ID is provided

### ISSUE THREAD

**Issue by kbgg** [source-cooperative/data.source.coop#5]
**Description of Bug:**

Authentication calls to the Source Cooperative API call an unimplemented route when an empty AWS_ACCESS_KEY_ID is provided to the data proxy.

**Steps to Reproduce:**
- Run `data.source.coop` locally
- Set `AWS_ACCESS_KEY_ID` environment variable to empty value (i.e. `export AWS_ACCESS_KEY_ID=`)
- Call any data proxy operation using the AWS CLI (i.e. `aws ls s3://planet/rapidai4eo/ --endpoint-url=http://localhost:8080`)

**Expected Behavior:**

Authentication method does not call the `{$SOURCE_API_URL}/api/v1/api-keys/{API_KEY}/auth` endpoint as we already know the user is making an unauthenticated request.

**Actual Behavior:**

Calls are made to the `{$SOURCE_API_URL}/api/v1/api-keys/auth` endpoint since the `reqwest` library transforms the request path from `/api/v1/api-keys//auth` to `/api/v1/api-keys/auth`. These requests cause a `501 - Not Implemented` error on the [Source Cooperative Frontend & API](https://github.com/source-cooperative/source.coop)

**Additional Context:**
![image](https://github.com/user-attachments/assets/2df601b1-e761-42a9-b791-a665690fbd4e)

**Comment by navdeepg2021** [comment]
Fixed.
